export const AVAILABLE_LANGS = ['en', 'es']
export const DEFAULT_COUNTRY = 'US'
export const DEFAULT_LANG = 'en'
export const COUNTRY_TO_CURRENCY = {
  'AR': 'ARS',
  'AU': 'AUD',
  'BO': 'BOV',
  'BZ': 'BZD',
  'CA': 'CAD',
  'CL': 'CLF',
  'CO': 'COU',
  'CR': 'CRC',
  'DE': 'EUR',
  'DO': 'DOP',
  'EC': 'USD',
  'ES': 'EUR',
  'GB': 'GBP',
  'GT': 'GTQ',
  'HN': 'HNL',
  'IE': 'EUR',
  'IN': 'INR',
  'JM': 'JMD',
  'JP': 'JPY',
  'MY': 'MYR',
  'MX': 'MXV',
  'NI': 'NIO',
  'NZ': 'NZD',
  'PA': 'USD',
  'PE': 'PEN',
  'PH': 'PHP',
  'PR': 'USD',
  'PY': 'PYG',
  'SG': 'SGD',
  'SV': 'USD',
  'TT': 'TTD',
  'US': 'USD',
  'UY': 'GYD',
  'VE': 'VES',
  'ZA': 'ZAR',
  'ZW': 'ZWL',
}
