export const AVAILABLE_LANGS = ['ar', 'en', 'es']
export const BASE_STRATEGY = 'minimumPayment'
export const DEFAULT_COUNTRY = 'US'
export const DEFAULT_LANG = 'en'
export const COUNTRY_TO_CURRENCY = {
  'AE': 'AED',
  'AR': 'ARS',
  'AT': 'EUR',
  'AU': 'AUD',
  'BE': 'EUR',
  'BH': 'BHD',
  'BO': 'BOV',
  'BR': 'BRL',
  'BZ': 'BZD',
  'CA': 'CAD',
  'CH': 'CHW',
  'CL': 'CLF',
  'CO': 'COU',
  'CR': 'CRC',
  'CZ': 'CZK',
  'DE': 'EUR',
  'DO': 'DOP',
  'DZ': 'DZD',
  'EC': 'USD',
  'EG': 'EGP',
  'ES': 'EUR',
  'FR': 'EUR',
  'GB': 'GBP',
  'GT': 'GTQ',
  'HN': 'HNL',
  'IE': 'EUR',
  'IN': 'INR',
  'IQ': 'IQD',
  'IT': 'EUR',
  'JM': 'JMD',
  'JO': 'JOD',
  'JP': 'JPY',
  'KW': 'KWD',
  'LB': 'LBP',
  'LI': 'CHF',
  'LU': 'EUR',
  'LY': 'LYD',
  'MA': 'MAD',
  'MC': 'EUR',
  'MX': 'MXV',
  'MY': 'MYR',
  'NI': 'NIO',
  'NZ': 'NZD',
  'OM': 'OMR',
  'PA': 'USD',
  'PE': 'PEN',
  'PH': 'PHP',
  'PR': 'USD',
  'PT': 'EUR',
  'PY': 'PYG',
  'QA': 'QAR',
  'RU': 'RUB',
  'SA': 'SAR',
  'SG': 'SGD',
  'SV': 'USD',
  'SY': 'SYP',
  'TN': 'TND',
  'TT': 'TTD',
  'US': 'USD',
  'UY': 'GYD',
  'VE': 'VES',
  'YE': 'YER',
  'ZA': 'ZAR',
  'ZW': 'ZWL',
}
export const STRATEGIES_ALL = [
  'minimumPayment',
  'highestRate', 'lowestBalance', 'balancePaymentRatio',
  'lowestRate', 'highestBalance' ,'balanceRateRatio']
export const STRATEGIES_SUGGESTED = [
  'highestRate', 'lowestBalance', 'balancePaymentRatio',
  'lowestRate', 'highestBalance' ,'balanceRateRatio']
