dependencies:
  /content/pages/home.yaml:
  - /content/partials/footer.yaml
  - /dist/css/composite/global.min.css
  - /dist/css/composite/home.min.css
  - /dist/js/composite/global.min.js
  - /dist/js/composite/home.min.js
  - /partials/debt/debt.html
  - /partials/footer.yaml
  - /partials/footer/footer.html
  - /partials/footer/footer.yaml
  - /partials/header/header.html
  - /partials/header/header.yaml
  - /partials/payment/payment.html
  - /static/images/favicon.png
objects: {}
