runtime: go112

handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html
- url: /(.*)/
  static_files: build/\1/index.html
  upload: build/.*/index\.html
- url: /(.*)
  static_files: build/\1
  upload: build/.*
